### ISSUE TITLE
Crash apparently at garbage collection

### ISSUE THREAD

**Issue by ip** [voodooattack/shared-buffer#4]
After my server processes a task using a shared buffer and manually detaches it, everything seems to work except that it crashes with this error:

```
#
# Fatal error in , line 0
# Check failed: Handle not reset in first callback. See comments on |v8::WeakCallbackInfo|..
#
#
#
#FailureMessage Object: 0x7ffeefbf3650[1]    13060 illegal hardware instruction  npm start
```

I use Node 10.15.0. Maybe it's because I'm detaching the buffer manually?

**Comment by voodooattack** [comment]
Can you please provide a minimal test able to reproduce this issue?

**Comment by ip** [comment]
> Can you please provide a minimal test able to reproduce this issue?

Unfortunately I couldn't reproduce it quickly and I don't have more time, but in my case disabling GC has helped - by commenting out `buffer.SetWeak(...)` line. Maybe it'll useful for you that I'm creating the segment in external process and then attaching to it in Node (`initialize` argument is `false`).

**Comment by voodooattack** [comment]
So the buffer wasn't originally created by node (via shared-buffer), but another process?

**Comment by voodooattack** [comment]
Fixed with v1.3.0.

**Comment by ip** [comment]
Thank you!

**Comment by kiranitian** [comment]
Hi, We have a similar issue in V8 7.2.504.22 version built for android. I tried keeping wrapper fix it doesn't solve the issue.

Log:
: Check failed: Handle not reset in first callback. See comments on |v8::WeakCallbackInfo|..

Could u please help us in solving the issue.?

Thanks,
Kiran

**Comment by voodooattack** [comment]
> Hi, We have a similar issue in V8 7.2.504.22 version built for android. I tried keeping wrapper fix it doesn't solve the issue.
> 
> Log:
> : Check failed: Handle not reset in first callback. See comments on |v8::WeakCallbackInfo|..
> 
> Could u please help us in solving the issue.?
> 
> Thanks,
> Kiran


Hi!

Unfortunately, I've no clue where to start when it comes to Android, and I have no experience with Android development. Any contributions are welcome though!
